#!/usr/bin/env node

const exec = require('child_process').exec;
const FQBN = "adafruit:samd:adafruit_pygamer_m4";
var PORT = "";

// execute a command and get output
const execute = (command, callback) => {
    exec(command, function(error, stdout, stderr) { callback(stdout, stderr); });
};

// abort program
const abort = (msg) => {
    console.log(msg);
    process.exitCode = -1;
    process.exit();
};

const log = (msg) => {
    console.log("\x1b[32m" + msg + "\x1b[0m");
}


if (require.main === module) {
    // get port
    execute("arduino-cli board list", (output, stderr) => {
        if (stderr.length !== 0)
            abort("Failed to locate device.");

        var devices = output.split('\n');

        devices.forEach((str, i) => {
            if (str.includes(FQBN)) {
                PORT = str.split(' ', 1)[0];
            }
        });

        if (PORT.length === 0)
            abort("Failed to locate device.");

        log("\t[✔] Port Found");

        // compile
        execute("arduino-cli compile --fqbn " + FQBN + " .", (output, stderr) => {
            if (stderr.length !== 0)
                abort(stderr);

            log("\t[✔] Compilation Successful");

            // upload
            execute("arduino-cli upload --fqbn " + FQBN + " --port " + PORT, (output, stderr) => {
                if (stderr.length !== 0)
                    abort(stderr);

                log("\t[✔] Upload Successful");
            });
        });
    });
}